app:
    name: "Http Bridge"
    version: 0.1

services:
    - name: "stripe"
      rate_limit: 500
      package:
          path: "parser.stripe"
          parser: "Webhook"
          request_identifier:
            id: "WebhookPayload.Id"
            default: "WebhookPayload.Id"
