app:
    name: "bridge"
    version: "0.1"

services:
    - name: "service1"
      parser: "parser-struct-name"
      rate_limit: 500
      identifier:
          id: "the-id-value"
          default: "the-default-value"
