name: Go Fmt

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go: ['1.22']

        name: Version ${{ matrix.go }} build.

        steps:
            - uses: actions/checkout@v4
            - name: "Setup GO"
              uses: actions/setup-go@v5
              with:
                  go-version: ${{ matrix.go }}
                  check-latest: true
                  cache-dependency-path: |
                      subdir/go.sum
                      tools/go.sum

            - name: "Test Installation"
              run: go version

            - name: Run Formatter
              run: gofmt -s -w
