name: Go Fmt

on: [pull_request]

jobs:
    formatter:
        strategy:
            matrix:
                go-version: [1.22.x]
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version: '^1.22' # The Go version to download (if necessary) and use.
            - run: go version
